DROP TABLE IF EXISTS NOTICE;
DROP TABLE IF EXISTS USER;

create table NOTICE
(
	ID	BIGINT auto_increment primary key,
	TITLE	VARCHAR(255),
	CONTENTS	VARCHAR(255),

	HITS	INTEGER,
	LIKES	INTEGER,
	REG_DATE	TIMESTAMP,
	UPDATE_DATE	TIMESTAMP,
	DELETED_DATE TIMESTAMP,
	DELETED	BOOLEAN
);

CREATE table user(
	ID BIGINT auto_increment primary key,
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(255),
	PHONE VARCHAR(255),
	REG_DATE TIMESTAMP,
	UPDATE_DATE TIMESTAMP,
	USER_NAME VARCHAR(255)
);